apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJhR0Z5YVc1cmFHRTZaMmh3WDFVMU0yaE1jRGR0UzNaVmFVeElhRUpQY1ZGS05ITjBRWFpyZVRCbGFETmxkMjFoVXc9PSJ9fX0=