apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker2deploy
  labels:
    app: worker2deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker2deploy
  template:
    metadata:
      labels:
        app: worker2deploy
    spec:
      containers:
      - name: worker2deploy
        image: ghcr.io/cs-muic/scalable-p2-scalable-t3-harinkha/worker2:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
            name: http
        env:
        - name: REDIS_HOST
          value: redisdeployment
        - name: REDIS_URL      
          value: redis
        - name: REDIS_PORT     
          value: '6379' 
        - name: MINIO_PORT
          value: '9000'
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          value: minio123  
      imagePullSecrets:
        - name: secret

---
apiVersion: v1
kind: Service
metadata:
  name: worker2deploy
spec:
  selector:
    app: worker2deploy
  type: ClusterIP  
  ports:
    - name: http
      port: 80
      targetPort: 5000
